#!/bin/bash
shopt -s extglob
# Convert a header file into a markdown file.
# Lines ending with '\' are aggregated before parsing.
# A comment starting on the same line as a piece of code is related to this code and should be printed out BEFORE that code and followed by ':'.
# Code and comments are trimmed of leading and trailing spaces.
# A comment ending with '.' is printed out followed by an empty line (md feature).
# Pieces of code are aggregated into code statements.
# A code statement is printed out preceded by '> ' (md feature).

# Text: concatenate a line ending with '\' with the next line.

# Pre-processor: lines starting with '#'.
# Pre-processor: "^#*([[:blank:]])define*\n".
# Pre-processor: "^#*([[:blank:]])include*\n".
# Pre-processor: ignore "^#*([[:blank:]])\n".
# Pre-processor: a comment is replaced by ' '.
# Pre-processor: trim leading and trailing spaces.

# Code: lines not starting with '#'.
# Code: a comment is replaced by ' '.
# Code: trim trailing spaces.
# Code: ignore empty lines.
# Code: prepend with '    '.

# Comment: "/* ... */".
# Comment: "// ...\n".
# Comment: trim leading and trailing spaces.
# Comment: replace trailing '.' by '.\n'.

typeset -i comment=0
typeset -i endcomment=0
typeset -i newpar=0
typeset -i verbatim=0
preline=
while IFS= read -r newline ; do
  preline="$preline${newline%"\\"}"
  if [[ "$newline" == *"\\" ]] ; then
    continue
  else
    line="$preline"
    preline=
  fi
  if (( comment )) && [[ "$line" == *([[:blank:]]) ]] ; then
    echo
    newpar=1
    verbatim=0
  fi
  if (( comment )) && (( newpar )) && [[ "$line" == +([[:blank:]])!([[:blank:]])* ]] ; then
    newpar=0
    verbatim=1
  fi
  while ! [[ "$line" == *([[:blank:]]) ]] ; do
          if ! (( comment )) && [[ "$line" == *"/*"*"*/"* ]] ; then
            a="${line#*"/*"}"
            a="${a%%"*/"*}"
            #a="${a//"."+([[:blank:]])/".\n\n"}"
            a="${a/%"."*([[:blank:]])/".\n"}"
            echo -e "\n${a#+([[:blank:]])}\n"
            code="$code ${line%%"/*"*}"
            line="${line#*"*/"}"
          elif ! (( comment )) && [[ "$line" == *"/*"* ]] ; then
            comment=1
            a="${line#*"/*"}"
            #a="${a//"."+([[:blank:]])/".\n\n"}"
            a="${a/%"."*([[:blank:]])/".\n"}"
            echo -e "\n${a#+([[:blank:]])}"
            code="$code${line%%"/*"*}"
            line=""
          elif (( comment )) && [[ "$line" == *"*/"* ]] ; then
            comment=0
            a="${line%%"*/"*}"
            #a="${a//"."+([[:blank:]])/".\n\n"}"
            if ! (( verbatim )) ; then
                    a="${a/%"."*([[:blank:]])/".\n"}"
                    echo -e "${a#+([[:blank:]])}\n"
            else
                    echo -n -e "\t" ; echo -E "${a%%+([[:blank:]])}"
            fi
            line="${line#*"*/"}"
            code="$code "
          elif (( comment )) ; then
            a="$line"
            #a="${a//"."+([[:blank:]])/".\n\n"}"
            if ! (( verbatim )) ; then
                    a="${a/%"."*([[:blank:]])/".\n"}"
                    echo -e "${a#+([[:blank:]])}"
            else
                    echo -n -e "\t" ; echo -E "${a%%+([[:blank:]])}"
            fi
            line=""
          elif ! (( comment )) && [[ "$line" == *"//"* ]] ; then
            a="${line#*"//"}"
            #a="${a//"."+([[:blank:]])/".\n\n"}"
            a="${a/%"."*([[:blank:]])/".\n"}"
            echo -e "\n${a#+([[:blank:]])}\n"
            code="$code${line%%"//"*}"
            line=""
          else
            code="$code$line"
            line=""
          fi
  done
  if [[ "$code" == "#"*([[:blank:]])"include"+([[:blank:]])* ]] ; then
    code="${code//"\\"/"\\\\"}"
    code="${code//"*"/"\\*"}"
    code="${code//"_"/"\\_"}"
    echo -n -e "\n| Include |\n| - |\n| "
    echo -n -E "${code#"#"*([[:blank:]])"include"+([[:blank:]])}"
    echo -e " |\n"
  elif [[ "$code" == "#"*([[:blank:]])"define"+([[:blank:]])* ]] ; then
    code="${code//"\\"/"\\\\"}"
    code="${code//"*"/"\\*"}"
    code="${code//"_"/"\\_"}"
    code="${code#"#"*([[:blank:]])"define"+([[:blank:]])}"
    echo -n -e "\n| Define | Value |\n| - | - |\n| "
    echo -n -E "${code/+([[:blank:]])/" | "}"
    echo -e " |\n"
  elif [[ "$code" == "#"* ]] ; then
    :
  elif [[ "$code" == *([[:blank:]])"typedef"+([[:blank:]])* ]] ; then
    code="${code//"\\"/"\\\\"}"
    code="${code//"*"/"\\*"}"
    code="${code//"_"/"\\_"}"
    code="${code#*([[:blank:]])"typedef"+([[:blank:]])}"
    code="${code%";"*([[:blank:]])}"
    echo -n -e "\n| Type definition |\n| - |\n| "
    echo -n -E "$code"
    echo -e " |\n"
  elif [[ "$code" != *([[:blank:]]) ]] ; then
    echo -n -e "\t" ; echo -E "$code"
  elif ! (( comment )) ; then
    echo
  fi
  code=""
done
